name: rag
channels:
  - conda-forge
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=2.135=mkl
  - blas-devel=3.9.0=35_h85df5b5_mkl
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cmake=4.2.0=hdcbee5b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpuonly=2.0=0
  - decorator=5.2.1=pyhd8ed1ab_0
  - diskcache=5.6.3=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastapi=0.123.9=h9db8b3a_0
  - fastapi-cli=0.0.16=pyhcf101f3_1
  - fastapi-core=0.123.9=pyhcf101f3_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py311h3485c13_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2025.3.0=h57928b3_641
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - krb5=1.21.3=hdf4eb48_0
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_0
  - libexpat=2.7.3=hac47afa_0
  - libfaiss=1.9.0=h3a9ed07_0_cpu
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblapacke=3.9.0=35_h3ae206f_mkl
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libuv=1.51.0=hfd05255_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - llama-cpp-python=0.3.16=py311h3e6a449_1
  - llama.cpp=6191=cpu_mkl_h9f38e57_1
  - llvm-openmp=20.1.8=h29ce207_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2024.2.2=h57928b3_16
  - mkl-devel=2024.2.2=h57928b3_16
  - mkl-include=2024.2.2=h57928b3_16
  - mpmath=1.3.0=pyhd8ed1ab_1
  - networkx=3.6=pyhcf101f3_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openssl=3.6.0=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pydantic-core=2.41.5=py311hf51aa87_1
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h0159041_2_cpython
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python_abi=3.11=8_cp311
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.3=py311h3f79411_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.0=pyhcf101f3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sniffio=1.3.1=pyhd8ed1ab_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - starlette-context=0.3.6=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - tk=8.6.13=h2c6b04d_3
  - tomli=2.3.0=pyhcf101f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - uvicorn=0.38.0=pyh5737063_0
  - uvicorn-standard=0.38.0=h5737063_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - watchfiles=1.1.1=py311h18438d6_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websockets=15.0.1=py311hf893f09_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==0.11.0
      - accelerate==0.34.2
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==3.7.1
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - bitsandbytes==0.49.0
      - bleach==6.3.0
      - brotli==1.2.0
      - build==1.3.0
      - cachetools==6.2.2
      - charset-normalizer==2.0.4
      - chromadb==1.3.5
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - distro==1.9.0
      - durationpy==0.10
      - ebooklib==0.17.1
      - einops==0.7.0
      - epub2txt==0.1.6
      - faiss-cpu==1.13.1
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - gradio==6.1.0
      - gradio-client==2.0.1
      - greenlet==3.3.0
      - groovy==0.1.2
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - instructorembedding==1.0.1
      - ipykernel==7.1.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - kubernetes==34.1.0
      - langchain==1.1.2
      - langchain-chroma==1.0.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.1
      - langchain-huggingface==1.1.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.12
      - langsmith==0.4.55
      - lark==1.3.1
      - lark-parser==0.12.0
      - logzero==1.7.0
      - lxml==6.0.2
      - marshmallow==3.26.1
      - mistune==3.1.4
      - mmh3==5.2.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nltk==3.9.2
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.39.0
      - opentelemetry-exporter-otlp-proto-common==1.39.0
      - opentelemetry-exporter-otlp-proto-grpc==1.39.0
      - opentelemetry-proto==1.39.0
      - opentelemetry-sdk==1.39.0
      - opentelemetry-semantic-conventions==0.60b0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.1.2
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - playwright==1.56.0
      - posthog==5.4.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - py4j==0.10.9.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.4
      - pydub==0.25.1
      - pyee==13.0.0
      - pypdf==6.4.1
      - pypdf2==3.0.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sse-starlette==2.1.3
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.9.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - urllib3==1.26.6
      - uuid-utils==0.12.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - xformers==0.0.33.post2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\dersi\miniconda3\envs\rag
